<?php



$boxids = [
'umdryebvlapkozostecnihjexg',
'amdryebalapkozfstwcnrhjqxg',
'umdcyebvlapaozfstwcnihjqgg',
'ymdryrbvlapkozfstwcuihjqxg',
'umdrsebvlapkozxstwcnihjqig',
'umdryibvlapkohfstwcnfhjqxg',
'umdryebvqapkozfatwcnihjqxs',
'umzrpebvlapkozfshwcnihjqxg',
'fmhryebvlapkozfstwckihjqxg',
'umdryebvlahkozfstwcnizjrxg',
'qmdryebvlapkozfslwcnihgqxg',
'umdiyebjlapknzfstwcnihjqxg',
'umdryebvlapkoqfstwcaihvqxg',
'cmdryebvlapkpzfstwcnihjvxg',
'umdryebvlakkozfstwcgihjixg',
'umdryebvlasjozfstwcnihqqxg',
'umdryebvladkozfsvwcnifjqxg',
'umdrlebvlapaozfstwcniwjqxg',
'umdryebvlhpkozrstwsnihjqxg',
'umdryebvcapkozfqtwcnihjrxg',
'ubdrykbvlapkowfstwcnihjqxg',
'umdryebvldpkozfstwcnihtqsg',
'umdryebvlapaozyutwcnihjqxg',
'umdryibvlapkozfstdfnihjqxg',
'umdryebvlapgozkstwznihjqxg',
'umdrxebvlapkozfstwcngxjqxg',
'umdryekvlapkozfstwclchjqxg',
'nmdryebvlapkozjsewcnihjqxg',
'umdryebvyapkozfstfcniheqxg',
'umdfyebvlapkozfstwcnhhjpxg',
'umdryelylupkozfstwcnihjqxg',
'smdryebvlqpkozfstwcnihjdxg',
'umdryebvlapaozfsuwcnihjqxc',
'umdryebvlrzkozrstwcnihjqxg',
'umdbycbvlapkojfstwcnihjqxg',
'umdryebvlapkonfstwpnirjqxg',
'uecryebvlapkozfstwcnihpqxg',
'uqdryebvltpkozfstwcnihrqxg',
'umdryebvlqsknzfstwcnihjqxg',
'cmdryebvlapkocfstwcvihjqxg',
'umdrkebvlapkozqsfwcnihjqxg',
'umdryabveapkoifstwcnihjqxg',
'ummrnehvlapkozfstwcnihjqxg',
'umdryebvlxpkozfstwqnihjtxg',
'umdryebvlagkozastwcnihjqxh',
'umdryebvlatkozzhtwcnihjqxg',
'umdryebvlcpkozfstwrnihjqvg',
'umdryebvlapkozfsnwcnrhjcxg',
'umdzyebvlypkozfstwcnibjqxg',
'nmdryebvlvpkozbstwcnihjqxg',
'uwdryebvlipkozfstwcnihvqxg',
'umdraebvlavkozfstwcnihjqwg',
'umdeyebvlspbozfstwcnihjqxg',
'umdryxlvlapkozfstwcnihjqxu',
'umdryegvlapkqzfstwcnirjqxg',
'umdrupbvlapkozfstwcnihjqog',
'imxryebvlapkxzfstwcnihjqxg',
'umdrfebvlapkozowtwcnihjqxg',
'umdreebvlapkozmstwczihjqxg',
'undryebdlapkozbstwcnihjqxg',
'umdryebvlapkpzfetwcnihjqxb',
'ymdnyebvlapkozfstwinihjqxg',
'umdryebvaapkozfstwcnihyqqg',
'umdryebvlapkzzwsrwcnihjqxg',
'umdrkebvlapkmzfskwcnihjqxg',
'umdrmebvlapkozfsvwcnidjqxg',
'umdlyehvlapkozfstwcnihjqkg',
'umnryebvlrpkozfstwjnihjqxg',
'uqdryebvlapxozfsawcnihjqxg',
'vmdruebvlapkozfstwcnihjqqg',
'umdryabviapkozistwcnihjqxg',
'umdryebvlapkzzfstwfnihkqxg',
'uvdryebvlapkozfsxwcuihjqxg',
'umdlhebvlapkozfstwcnvhjqxg',
'umdreebvlapkopfstjcnihjqxg',
'umdryebvlazkomfstwynihjqxg',
'kmdryebulapkoznstwcnihjqxg',
'umdryebvxakkozfstwinihjqxg',
'ukdryobvlapkozistwcnihjqxg',
'umdryebveapkozfstwcnthjqgg',
'mmdrtebvlapcozfstwcnihjqxg',
'umdryebvlapkolistwnnihjqxg',
'umdryebxlapkozfatwcnihjqxx',
'uxdryebvlapkozfstwhniheqxg',
'ufdryebvzapkozfstwcnbhjqxg',
'amdryhbvlapkozfstwcnifjqxg',
'umqryebvlaphozfstwcnihjqxn',
'umdryebvlapkosfstfcnihjqxe',
'gmkryebvlapkozfstwcnihjmxg',
'umdrnebvlkpkozfstwcnihjnxg',
'umdryebvrapkozfstmcndhjqxg',
'umdryebvmapkozfstichihjqxg',
'umdryesvnapkozestwcnihjqxg',
'umeryhbvlapkozfstfcnihjqxg',
'umdryedvbapkozfstwcnihqqxg',
'umdryebllapzozfstwcnihjvxg',
'umdcyebvlzdkozfstwcnihjqxg',
'umdrybbvlapkbvfstwcnihjqxg',
'umdrytbglapkozfsthcnihjqxg',
'umdryebvlkpkozfsteclihjqxg',
'umdntebvlapkmzfstwcnihjqxg',
'lkdryebveapkozfstwcnihjqxg',
'ymdryubvlapkozfstwbnihjqxg',
'tmrryebvlapkozfstwcnqhjqxg',
'umdryeovlaekonfstwcnihjqxg',
'umiryeuvlapkozfstwcnihjwxg',
'umdryebvlspvozwstwcnihjqxg',
'umdrtebvlapkoznxtwcnihjqxg',
'umvryebvlaphozfstwcnahjqxg',
'umdryebvlapkozfstinniajqxg',
'umdryebqlapkozfctwcnihjqxx',
'umdryebvlapkbzfptwcnihjqvg',
'umdryabviapkozistwcnihjqxd',
'umdryrbvlapkezfstscnihjqxg',
'umhryebvlapkozfstacnihxqxg',
'umdxyelvlapkozfitwcnihjqxg',
'umdryevvuapkozfstwcnihtqxg',
'uydrypbvxapkozfstwcnihjqxg',
'umdryebvlapkopfstwcnihzqxo',
'uedryebvlapkozistwceihjqxg',
'umdiyebvlapkozfgtwcnihjqxv',
'ymdryebvlapkozfsticniqjqxg',
'umbrkebvlapkozfslwcnihjqxg',
'umdryebliapkozbstwcnihjqxg',
'umvryebolapkozfstwcnihjqig',
'umdryeavbackozfstwcnihjqxg',
'umdryfbvlapsozfstwcnihaqxg',
'umdqyebvlapkozfjtgcnihjqxg',
'umdrjebvlaqkozfstwcyihjqxg',
'umdryebklaqkozrstwcnihjqxg',
'umdryebvpapkozfstwcpihjqjg',
'uydryebhlawkozfstwcnihjqxg',
'umdyyebvlapkozfstwcykhjqxg',
'umdryebvlapkozfstwcnitjnxh',
'umdzyebvlapkozfstwcnehyqxg',
'mmcryebvlapkozfstwinihjqxg',
'umdryebvlapuozfstwmvihjqxg',
'umdryfbvlapkozqstwcnihjmxg',
'umdryebslapsozfhtwcnihjqxg',
'umdtyemvlapmozfstwcnihjqxg',
'umdrxevvlapkozfytwcnihjqxg',
'umdahebvlapjozfstwcnihjqxg',
'umdryebvlapkozfstacnivjqxb',
'umdryebvlzpkozfjtwcnihjyxg',
'umdryebvlaqkozfstwcnisjqxu',
'umdrydbvlapkozfsuwcnihjlxg',
'umdryebvlapkomrstwcnihjqkg',
'umdryebvlapcozfstmcnwhjqxg',
'umdryebvlahkozfstwcibhjqxg',
'gmdrzebvlapkozlstwcnihjqxg',
'umdryebvlapkezfsswcnrhjqxg',
'umdryebvlapkoqfitwcgihjqxg',
'umdrnebvlapkozfsiwcninjqxg',
'umdryebvlapkozfsrwckohjqxg',
'umdryebtlapkomfstwcnihjexg',
'umdryxbvlapjozfstwcnihoqxg',
'umdpyebvlapkosustwcnihjqxg',
'umdryebvlapkvzfawwcnihjqxg',
'umhnyebvlaikozfstwcnihjqxg',
'umdryebvlagkozfstvknihjqxg',
'uodryebjlapkoxfstwcnihjqxg',
'umdryefdlapkozfstwcnyhjqxg',
'umprmebvtapkozfstwcnihjqxg',
'umdhyebvlapoozfstwcnihjqgg',
'uddryebvidpkozfstwcnihjqxg',
'umdryebtlapkozfetwfnihjqxg',
'umdbyebolapkozfstwcoihjqxg',
'umdryebvlapkonfstwcnihjpxo',
'umdryebvlapkohfstwcnihjqwk',
'umdryebolalkkzfstwcnihjqxg',
'updryebvxapkozfstwcnshjqxg',
'umdryebvlapkovfktwcnuhjqxg',
'umdrqrbvlppkozfstwcnihjqxg',
'umdrylgvlapkozfstwrnihjqxg',
'umdryebvlapkozfstxcnihbqig',
'uvdryeevlappozfstwcnihjqxg',
'zmdryebvlapkozfstwcnihqqxt',
'umdryebvlapvozfstwenihiqxg',
'umdryebvlbpkozfsgwcnihjlxg',
'umdryhbvlapkozfstwcnihtqxw',
'umdreecvlapkozwstwcnihjqxg',
'umwryebvlapkoztsmwcnihjqxg',
'ukdryebvfapkozrstwcnihjqxg',
'umdrylbdlamkozfstwcnihjqxg',
'umdryebvlapoozwsmwcnihjqxg',
'umdryebvlapkozfqtwcnnzjqxg',
'umdryekvlapktzfstwcnohjqxg',
'umdryebvlapkozfstwcnihjwqo',
'umdrrebflapkogfstwcnihjqxg',
'umdryevvlapkozfztwctihjqxg',
'umdrybbvlapkozfstwcnihxaxg',
'umdryebvlapkozfsowcnphjqag',
'smdryebvlapbozfitwcnihjqxg',
'umdryebvtapiozfstwcnihjqxe',
'umdryebjlakkozfstwccihjqxg',
'umdryebvlapdozfshwckihjqxg',
'umnryebvlapiozfstwcnihlqxg',
'umdrycbvlapkjzfsnwcnihjqxg',
'umdryebvyaprozjstwcnihjqxg',
'ucdryebvlapkozfstwomihjqxg',
'umdryebvlagklzfstwcnihjqyg',
'umdryebvladkozfstwcnihjqjh',
'umdrwebvlapkozfstwdnicjqxg',
'umdryebvlapkmzfstwcniheqxr',
'umdryebvlapkjzfstwcviheqxg',
'umdrvebvlapkozfstwcbihjqmg',
'umdrfebvlapkoffstwcnihsqxg',
'umdryebvtarkazfstwcnihjqxg',
'umdryebvlapkozfstwcfihjcng',
'umdryebvlapkktostwcnihjqxg',
'uedryeevlapkozfstwcniijqxg',
'bmdryebylapkozfstwcnihjqog',
'umdryebvlmpkoztstwcnihjqeg',
'umdryepvlarkohfstwcnihjqxg',
'uwdryebvlapklzfstzcnihjqxg',
'umdryebklapkozfsswcbihjqxg',
'umdtyeavlapkozfstwsnihjqxg',
'umdryebvaapkozfhtfcnihjqxg',
'umdrpebvlapuozfstwvnihjqxg',
'umdryebvlapkozffmwcniijqxg',
'uqdpyebvlapkozfstwfnihjqxg',
'umdryebvlapuozdstwcnihjhxg',
'tmdryhbvlapkozfptwcnihjqxg',
'umdryevvmapkozfstwcnihjgxg',
'umdryeuvlapmozfstwcnihjwxg',
'umdryebqlzpkozfbtwcnihjqxg',
'umdryebvsapkozystwcniqjqxg',
'imdryebvlapkozfscwinihjqxg',
'umdryebvlzpkozustwcnmhjqxg',
'umdrypbvlapbozfsnwcnihjqxg',
'bmdryebvlapqoznstwcnihjqxg',
'umdrfebvlapaozfstwcnihxqxg',
'umdiyebvxapkozfstwcnchjqxg',
'umdrygbvlapkozfstwcnizjqxz',
'amdryedvlapkozfstwcnihfqxg',
'umdryebvvapzozfstwcnihjgxg',
'undryebvlapkzzfstjcnihjqxg',
'umdryvbvlapgozfrtwcnihjqxg',
'umdrkebvlapkozfstwcnihihxg',
'umdryebvrppkozfsowcnihjqxg',
'umdryebvlapktzfsdwclihjqxg',
'otdrdebvlapkozfstwcnihjqxg',
'mmdryebvlazkozfxtwcnihjqxg',
'umdryebvlapkozfsbwtnihjqxa',
'imqryebvrapkozfstwcnihjqxg',
'umdryebvlrpkozfscwcnihjqlg',
'uedryebvlapkoznsvwcnihjqxg',
'umdryebvlqpkozfstscnihjqxj',
'umerycbvlapkozfstwcnihjqxh',
'umdkykbvlapjozfstwcnihjqxg',
];


$i2 = 0;
$i3 = 0;
foreach($boxids as $id) {
    $p = str_split($id);
    $p = array_count_values($p);
    $p = array_flip($p);


    if( isset($p[2]) ) $i2++; 
    if( isset($p[3]) ) $i3++; 
}

print "part 1: " . ($i2 * $i3) . "\n";

$match = ['count' => 9999, 'box1' => null, 'box2' => null];
foreach($boxids as $box1) {
    foreach($boxids as $box2) {
            if($box1 === $box2) continue;

            $count = levenshtein($box1, $box2, 999,1,999);
            if($match['count'] > $count) {
                $match['count'] = $count;
                $match['box1'] = $box1;
                $match['box2'] = $box2;
            }
    }
}


print "part2 : {$match['count']} ({$match['box1']} : {$match['box2']})";